### ISSUE TITLE
Problem when using text-decoration.

### ISSUE THREAD

**Issue by pedrokermitgoncalves** [SaraVieira/postcss-caralho#1]
Hi Sara, there's a problem with your caralho.

When you use the css prop "text-decoration" it will transpile to "text-decoloration"

I belive it is due to uour replace here:

`decl.prop = decl.prop.replace('cor', 'color')`
`decl.prop = decl.prop.replace('decoracao-texto', 'text-decoration')`

All TVG@Mindera folks :P

**Comment by SaraVieira** [comment]
@pedrokermitgoncalves fixed in 1.0.1
