### ISSUE TITLE
Word Translations

### ISSUE THREAD

**Issue by lovelldies** [SaraVieira/postcss-caralho#11]
I think we should provide the translations (next to the curse words) in the README file, so that we can choose to curse in foreign languages whenever we wish.

**Comment by SaraVieira** [comment]
That is a great idea !

All translations should be to english right ?

**Comment by lovelldies** [comment]
Yes. English would be ideal. Since most (if not all) code is written in English.

**Comment by SaraVieira** [comment]
Sure then! 

I'll get on this today 😄

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lovelldies** [comment]
I'll translate the Konkani & Hindi words one of these days.

**Comment by SaraVieira** [comment]
That would be awesome @lovelldies!
